# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "byebug"
gem "sinatra"
gem "activerecord"
gem "sqlite3"
gem "rackup", "~> 2.2"
gem "puma", "~> 7.0"
# gem 'paginify', path: '../paginify' # for test in localhost
gem 'paginify', git: 'git@github.com:solehudinmq/paginify.git', branch: 'main'